pipeline {
    agent any


    stages {
        stage('init') {
            steps {
                git([url: 'https://github.com/gokulraja2787/trader-ops.git', branch: 'main'])
            }
        }

        stage('pack artifact') {
            steps {
                sh "cd  trader-db"
                sh "pwd && ls -lrth"
                sh "tar -cf trader-db.rar *.sh"
            }
        }
        
        stage('Copy scripts to remote host') {
            /*withCredentials([usernamePassword(credentialsId: 'virtu-server-credential', passwordVariable: 'password', usernameVariable: 'userName')]){
                remote.user = userName
                remote.password = password
            }
            sshagent(credentials : ['jenkins-pem']) {
            sh "echo pwd"
            sh 'ssh -t -t ubuntu@xx.xxx.xx.xx -o StrictHostKeyChecking=no "echo pwd && sudo -i -u root && cd /opt/docker/web && echo pwd"'
            }*/
            steps {
                script {
                    sh 'pwd'
                    sshPublisher( continueOnError: false, failOnError: true, publishers: [
                        sshPublisherDesc(
                            configName: "virtu-server",
                            verbose: true,
                            transfers: [
                            sshTransfer(
                                sourceFiles: "trader-db.rar",
                                execCommand: "tar -xf trader-db.rar"
                            )
                        ])
                    ])
                }
            }
        }
    }
}