pipeline {
    agent any

    environment {
        RCREDS = credentials('virtu-server-credential')
    }

    stages {
        stage('init') {
            steps {
                git([url: 'https://github.com/gokulraja2787/trader-ops.git', branch: 'main'])
            }
        }

        stage('pack artifact') {
            steps {
                sh "cd trader-db && tar -cvf trader-db.rar *.sh"
            }
        }
        
        stage('Copy scripts to remote host') {
            /*withCredentials([usernamePassword(credentialsId: 'virtu-server-credential', passwordVariable: 'password', usernameVariable: 'userName')]){
                remote.user = userName
                remote.password = password
            }
            sshagent(credentials : ['jenkins-pem']) {
            sh "echo pwd"
            sh 'ssh -t -t ubuntu@xx.xxx.xx.xx -o StrictHostKeyChecking=no "echo pwd && sudo -i -u root && cd /opt/docker/web && echo pwd"'
            }*/
            steps {
                script {
                    sh 'pwd'

                    def remote = [:]
                    remote.host="$rhost"
                    remote.name="$rname"
                    remote.allowAnyHosts = true
                    remote.user = "$RCREDS_USR"
                    remote.password = "$RCREDS_PSW"

                    echo "Remove old rar"
                    sshCommand remote: remote, command: "rm staging/trader-db.rar"

                    echo "Copy new rar"
                    sshPublisher( continueOnError: false, failOnError: true, publishers: [
                        sshPublisherDesc(
                            configName: "virtu-server",
                            verbose: true,
                            transfers: [
                                sshTransfer(
                                    sourceFiles: "trader-db/trader-db.rar"
                                )
                        ])
                    ])

                    echo "Extract tar"
                    sshCommand remote: remote, command: "cd ~/live/trader-db && rm -f *.sh  && tar -xvf ~/staging/trader-db.rar"
                }
            }
        }
    }
}